# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.


name: UI Test Automation

on:
  schedule:
    - cron: '0 0 * * 1,4' # Runs at 00:00 (midnight UTC) on Monday and Thursday
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  ui_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin' # Recommended OpenJDK distribution

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable # Or specify a specific version if needed

      - name: Get Chrome version
        id: chrome-version
        run: echo "CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3)" >> $GITHUB_OUTPUT

      - name: Display Chrome and ChromeDriver versions
        run: |
          echo "Chrome Version: ${{ steps.chrome-version.outputs.CHROME_VERSION }}"
          echo "ChromeDriver Version: $(chromedriver --version)"

      - name: Set up Maven
        uses: actions/setup-maven@v4
        with:
          maven-version: '3.9.x' # Or your preferred Maven version

      - name: Run UI Tests (Headless)
        run: mvn clean test -Dbrowser=chrome-headless

      - name: Publish Test Report (Optional - configure your reporting tool)
        if: always() # Run even if tests fail
        # Add steps to publish your test reports (e.g., using a reporting action or uploading artifacts)
        # Example using built-in upload-artifact (basic)
        # uses: actions/upload-artifact@v3
        # with:
        #   name: test-report
        #   path: path/to/your/test-reports # Adjust this path

            # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
